[build]
  publish = "dist/public"
  command = "npm install && npm run netlify:build"

[build.environment]
  NODE_VERSION = "18"

# Visual Editor dev command  
[dev]
  command = "npm run dev --prefix client"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200