[build]
  publish = "dist/public" 
  command = "npm run build:client"

[build.environment]
  NODE_VERSION = "18"

# Enable Visual Editor
[template]
  incoming-hooks = ["stackbit"]

[build.processing]
  skip_processing = false
  
# Visual Editor configuration
[context.deploy-preview.environment]
  STACKBIT_API_URL = "https://api.stackbit.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist/public"

# Headers pour optimiser les performances
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache des assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache des images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"