[build]
  publish = "dist/public"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Visual Editor dev command
[dev]
  command = "cd client && npm run dev"
  port = 5173
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200